### ISSUE TITLE
4.5.5 版本 no_pay, iOS 打包失败

### ISSUE THREAD

**Issue by Albert556** [OpenFlutter/fluwx#611]
**Describe the bug**
iOS 使用 4.5.5 版本的 fluwx 会编译失败

fluwx 配置
```yaml

fluwx:
  app_id: 123456
  #  only debug in debug mode
  debug_logging: true
  #  interrupt_wx_request: true # default is true
  #  flutter_activity: MainActivity #Default to launch app's launcher
  ios:
    universal_link:
    #    scene_delegate: true #default false
    #    payment is enabled by default
    no_pay: true

```

Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): Library 'WechatOpenSDK' not found

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

**To Reproduce**
flutter run

**Which version of Fluwx do you use?**
4.5.5 

**Which device do you run on**
iPhone XR，iOS 17.4.1

**Which Flutter do you use?**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.88.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
